apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: causa-backend
  labels:
    app.kubernetes.io/name: causa-backend
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: causa.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: causa-backend
            port:
              name: http
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: causa-backend
            port:
              name: http
