apiVersion: apps/v1
kind: Deployment
metadata:
  name: causa-backend
spec:
  template:
    metadata:
      annotations:
        # OpenShift-specific annotations
        openshift.io/scc: restricted
    spec:
      # OpenShift security context
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: causa-backend
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
