apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: quay.io/rh-ee-shesaxen/causa-backend
    newTag: latest_mvp
