apiVersion: v1
kind: ServiceAccount
metadata:
  name: causa-backend
  labels:
    app.kubernetes.io/name: causa-backend
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: causa
