package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;

/**
 * Alert JPA Entity — maps to the {@code alerts} table.
 *
 * <p>Stores Prometheus Alertmanager webhook ingestion data.
 * Column names are derived automatically from field names via
 * {@code CamelCaseToUnderscoresNamingStrategy}.
 *
 * <p>ID convention: {@code alrt_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "alerts")
public class AlertEntity extends BaseEntity {

    /** Application-generated PK: {@code alrt_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Fingerprint / source ID from the upstream alert system (e.g. Prometheus fingerprint). */
    @Column(nullable = false, length = 255)
    private String sourceAlertId;

    /** Human-readable alert name (e.g. {@code HighMemoryUsage}). */
    @Column(nullable = false, length = 255)
    private String alertName;

    /** When the alert was fired by Prometheus. Nullable for resolved-only webhooks. */
    @Column
    private OffsetDateTime alertTimestamp;

    /** Alert severity: {@code critical}, {@code warning}, or {@code info}. */
    @Column(length = 32)
    private String severity;

    /**
     * Processing lifecycle status within Causa.
     * Values: {@code ACCEPTED}, {@code REJECTED}, {@code PROCESSING}, {@code PROCESSED}.
     */
    @Column(nullable = false, length = 32)
    private String status;

    /**
     * Container metadata from Prometheus labels/annotations stored as JSONB.
     * Shape: {@code { "name": "...", "namespace": "...", "pod": "..." }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode containerInfo;

    /** Extracted container name for fast indexed lookups (denormalised from containerInfo). */
    @Column(nullable = false, length = 255)
    private String containerName;

    /**
     * Catch-all JSONB bag for raw Prometheus labels, annotations, and any future fields.
     * Shape: {@code { "labels": {...}, "annotations": {...} }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode alertMetadata;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getSourceAlertId() { return sourceAlertId; }
    public void setSourceAlertId(String sourceAlertId) { this.sourceAlertId = sourceAlertId; }

    public String getAlertName() { return alertName; }
    public void setAlertName(String alertName) { this.alertName = alertName; }

    public OffsetDateTime getAlertTimestamp() { return alertTimestamp; }
    public void setAlertTimestamp(OffsetDateTime alertTimestamp) { this.alertTimestamp = alertTimestamp; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public JsonNode getContainerInfo() { return containerInfo; }
    public void setContainerInfo(JsonNode containerInfo) { this.containerInfo = containerInfo; }

    public String getContainerName() { return containerName; }
    public void setContainerName(String containerName) { this.containerName = containerName; }

    public JsonNode getAlertMetadata() { return alertMetadata; }
    public void setAlertMetadata(JsonNode alertMetadata) { this.alertMetadata = alertMetadata; }
}
