package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Auth Configuration JPA Entity — maps to the {@code auth_configurations} table.
 *
 * <p>Stores reusable authentication configurations for LLM providers and MCP servers.
 * Sensitive configuration values are stored in {@code config} with field-level encryption.
 *
 * <p>ID convention: {@code auth_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "auth_configurations")
public class AuthConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code auth_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Unique human-readable name (e.g. {@code anthropic-api-key}). */
    @Column(nullable = false, length = 255, unique = true)
    private String name;

    /** Authentication type: API_KEY, BEARER_TOKEN, ADC, NONE. */
    @Column(nullable = false, length = 32)
    private String type;

    /** Auth-type-specific configuration with field-level encryption. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode config;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    public JsonNode getConfig() { return config; }
    public void setConfig(JsonNode config) { this.config = config; }
}
