package com.causa.infrastructure.persistence.entity;

import jakarta.persistence.*;

/**
 * Configuration JPA Entity — maps to the {@code configurations} table.
 *
 * <p>Stores global cluster run parameters and microservice feature flags as key-value pairs.
 * Keys must be unique; values are stored as plain text (optionally encrypted at the
 * application layer when {@code isEncrypted} is {@code true}).
 *
 * <p>ID convention: {@code cnfg_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "configurations")
public class ConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code cnfg_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Unique configuration key (e.g. {@code feature.rag.enabled}). */
    @Column(nullable = false, length = 255, unique = true)
    private String configKey;

    /** Configuration value. May be encrypted — check {@link #isEncrypted()}. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String configValue;

    /** When {@code true} the application layer must decrypt {@code configValue} before use. */
    @Column(nullable = false)
    private Boolean isEncrypted = false;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getConfigKey() { return configKey; }
    public void setConfigKey(String configKey) { this.configKey = configKey; }

    public String getConfigValue() { return configValue; }
    public void setConfigValue(String configValue) { this.configValue = configValue; }

    public Boolean isEncrypted() { return isEncrypted; }
    public void setEncrypted(Boolean encrypted) { this.isEncrypted = encrypted; }
}
