package com.causa.infrastructure.persistence.entity;

import jakarta.persistence.*;

/**
 * Feedback JPA Entity — maps to the {@code feedback} table.
 *
 * <p>Stores SRE ratings and comments on a completed diagnostic analysis.
 * Both {@code diagnosticsId} and {@code alertId} are stored for fast indexed access.
 *
 * <p>ID convention: {@code fdbk_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "feedback")
public class FeedbackEntity extends BaseEntity {

    /** Application-generated PK: {@code fdbk_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /**
     * FK to {@code diagnostics.id}. Loaded lazily.
     * Use {@link #getDiagnosticsId()} to access the ID without triggering a join.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "diagnostics_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_feedback_diagnostics"))
    private DiagnosticEntity diagnostics;

    /**
     * FK to {@code alerts.id}. Loaded lazily.
     * Use {@link #getAlertId()} to access the ID without triggering a join.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alert_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_feedback_alert"))
    private AlertEntity alert;

    /** SRE rating from 1 (poor) to 5 (excellent). Nullable until explicitly rated. */
    @Column
    private Integer rating;

    /** Free-text remarks from the SRE. */
    @Column(columnDefinition = "TEXT")
    private String remarks;

    /** Whether the SRE found the analysis section useful. */
    @Column(nullable = false)
    private Boolean analysisLiked = false;

    /** Whether the SRE found the solution section useful. */
    @Column(nullable = false)
    private Boolean solutionLiked = false;

    // -------------------------------------------------------------------------
    // Convenience accessors
    // -------------------------------------------------------------------------

    public String getDiagnosticsId() {
        return diagnostics != null ? diagnostics.getId() : null;
    }

    public String getAlertId() {
        return alert != null ? alert.getId() : null;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public DiagnosticEntity getDiagnostics() { return diagnostics; }
    public void setDiagnostics(DiagnosticEntity diagnostics) { this.diagnostics = diagnostics; }

    public AlertEntity getAlert() { return alert; }
    public void setAlert(AlertEntity alert) { this.alert = alert; }

    public Integer getRating() { return rating; }
    public void setRating(Integer rating) { this.rating = rating; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }

    public Boolean getAnalysisLiked() { return analysisLiked; }
    public void setAnalysisLiked(Boolean analysisLiked) { this.analysisLiked = analysisLiked; }

    public Boolean getSolutionLiked() { return solutionLiked; }
    public void setSolutionLiked(Boolean solutionLiked) { this.solutionLiked = solutionLiked; }
}
