package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Health Check JPA Entity — maps to the {@code health_checks} table.
 *
 * <p>Stores Causa engine heartbeat snapshots. Rows older than 15 days are pruned by a scheduler.
 * Column names are derived automatically from field names via
 * {@code CamelCaseToUnderscoresNamingStrategy}.
 *
 * <p>ID convention: {@code hchk_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "health_checks")
public class HealthCheckEntity extends BaseEntity {

    /** Application-generated PK: {@code hchk_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Overall health status: {@code UP}, {@code DEGRADED}, or {@code DOWN}. */
    @Column(nullable = false, length = 32)
    private String overallStatus;

    /**
     * Component-level health details stored as JSONB.
     * Shape: {@code { "database": { "status": "UP", "responseTime": 12 }, "llm": { ... } }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode componentInfo;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getOverallStatus() { return overallStatus; }
    public void setOverallStatus(String overallStatus) { this.overallStatus = overallStatus; }

    public JsonNode getComponentInfo() { return componentInfo; }
    public void setComponentInfo(JsonNode componentInfo) { this.componentInfo = componentInfo; }
}
