package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Integration JPA Entity — maps to the {@code integrations} table.
 *
 * <p>Stores outbound integration targets (Slack, Jira, Datadog, GitHub).
 * Each platform is unique — only one configuration per platform is permitted.
 *
 * <p>ID convention: {@code intg_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "integrations")
public class IntegrationEntity extends BaseEntity {

    /** Application-generated PK: {@code intg_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /**
     * Target platform identifier. Unique — one config per platform.
     * Values: {@code JIRA}, {@code SLACK}, {@code DATADOG}, {@code GITHUB}.
     */
    @Column(nullable = false, length = 64, unique = true)
    private String targetPlatform;

    /**
     * Platform-specific connection details stored as JSONB.
     * Shape is platform-dependent; e.g. Slack: {@code { "webhook_url": "..." }},
     * Jira: {@code { "base_url": "...", "project_key": "..." }}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode targetDetails;

    /** Whether this integration is currently active. */
    @Column(nullable = false)
    private Boolean isActive = true;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTargetPlatform() { return targetPlatform; }
    public void setTargetPlatform(String targetPlatform) { this.targetPlatform = targetPlatform; }

    public JsonNode getTargetDetails() { return targetDetails; }
    public void setTargetDetails(JsonNode targetDetails) { this.targetDetails = targetDetails; }

    public Boolean isActive() { return isActive; }
    public void setActive(Boolean active) { this.isActive = active; }
}
