package com.causa.infrastructure.persistence.entity;

import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import org.hibernate.annotations.Type;

/**
 * LLM Configuration JPA Entity — maps to the {@code llm_configurations} table.
 *
 * <p>Defines the LLM models available to the application, including their provider,
 * model configuration, authentication, and runtime settings.
 *
 * <p>ID convention: {@code llmc_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "llm_configurations")
public class LlmConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code llmc_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Unique human-readable name (e.g. {@code Anthropic Direct}). */
    @Column(nullable = false, length = 255, unique = true)
    private String name;

    /** Provider identifier (e.g. {@code anthropic}, {@code vertex-ai-anthropic}, {@code bob}). */
    @Column(nullable = false, length = 64)
    private String provider;

    /** Model identifier (e.g. {@code claude-sonnet-4-6}). */
    @Column(nullable = false, length = 255)
    private String model;

    /** Foreign key to {@code auth_configurations}; nullable. */
    @Column(length = 21)
    private String authId;

    /** Runtime configuration (temperature, max_tokens, timeout, skills config, etc.). */
    @Type(JsonBinaryType.class)
    @Column(nullable = false, columnDefinition = "jsonb")
    private String settings;

    /** Only one provider should be active at a time. */
    @Column(nullable = false)
    private Boolean isActive = false;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getProvider() { return provider; }
    public void setProvider(String provider) { this.provider = provider; }

    public String getModel() { return model; }
    public void setModel(String model) { this.model = model; }

    public String getAuthId() { return authId; }
    public void setAuthId(String authId) { this.authId = authId; }

    public String getSettings() { return settings; }
    public void setSettings(String settings) { this.settings = settings; }

    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }
}
