package com.causa.infrastructure.persistence.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * MCP Configuration JPA Entity — maps to the {@code mcp_configurations} table.
 *
 * <p>Stores MCP server definitions, including connection endpoints, available tools,
 * skills, authentication, and server-specific runtime settings.
 *
 * <p>ID convention: {@code mcpc_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "mcp_configurations")
public class McpConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code mcpc_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Unique human-readable server name (e.g. {@code kubernetes}). */
    @Column(nullable = false, length = 255, unique = true)
    private String name;

    /** MCP server endpoint. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String url;

    /** Health-check URL or path. */
    @Column(columnDefinition = "TEXT")
    private String healthUrl;

    /** Array of available tool names (e.g. {@code ["pods_get", "pods_log"]}). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode tools;

    /** Foreign key to {@code auth_configurations}; nullable. */
    @Column(length = 21)
    private String authId;

    /** Server-specific configuration (timeout_ms, retry config, platform, etc.). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private JsonNode settings;

    /** Active by default. */
    @Column(nullable = false)
    private Boolean active = true;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }

    public String getHealthUrl() { return healthUrl; }
    public void setHealthUrl(String healthUrl) { this.healthUrl = healthUrl; }

    public JsonNode getTools() { return tools; }
    public void setTools(JsonNode tools) { this.tools = tools; }

    public String getAuthId() { return authId; }
    public void setAuthId(String authId) { this.authId = authId; }

    public JsonNode getSettings() { return settings; }
    public void setSettings(JsonNode settings) { this.settings = settings; }

    public Boolean getActive() { return active; }
    public void setActive(Boolean active) { this.active = active; }
}
