package com.causa.infrastructure.persistence.entity;

import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Skill Configuration JPA Entity — maps to the {@code skills_configurations} table.
 *
 * <p>Stores reusable skill definitions. A skill can be provided inline as Markdown,
 * loaded from a local path, or retrieved from a remote URL.
 *
 * <p>ID convention: {@code sklc_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "skills_configurations")
public class SkillConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code sklc_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Foreign key to {@code mcp_configurations}. */
    @Column(nullable = false, length = 21)
    private String mcpConfigurationId;

    /** Human-readable skill name. */
    @Column(nullable = false, length = 255)
    private String name;

    /** Skill source: INLINE, PATH, or URL. */
    @Column(nullable = false, length = 16)
    private String sourceType;

    /** File path or remote URL; nullable for INLINE skills. */
    @Column(columnDefinition = "TEXT")
    private String uri;

    /** Markdown skill content; primarily used for INLINE skills. */
    @Column(columnDefinition = "TEXT")
    private String content;

    /** Optional structured metadata (description, tags, configuration). */
    @Type(JsonBinaryType.class)
    @Column(columnDefinition = "jsonb")
    private String metadata;

    /** Active by default. */
    @Column(nullable = false)
    private Boolean isActive = true;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getMcpConfigurationId() { return mcpConfigurationId; }
    public void setMcpConfigurationId(String mcpConfigurationId) { this.mcpConfigurationId = mcpConfigurationId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getSourceType() { return sourceType; }
    public void setSourceType(String sourceType) { this.sourceType = sourceType; }

    public String getUri() { return uri; }
    public void setUri(String uri) { this.uri = uri; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }

    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }
}
