package com.causa.infrastructure.persistence.entity;

import com.causa.common.constants.ConfigConstants.SkillSourceType;
import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Skill Configuration JPA Entity — maps to the {@code skills_configurations} table.
 *
 * <p>Stores reusable skill definitions. A skill can be provided inline as Markdown,
 * loaded from a local path, or retrieved from a remote URL.
 *
 * <p>ID convention: {@code sklc_<16-char-alphanumeric>} — generated by the application layer.
 *
 * @since 0.0.1
 */
@Entity
@Table(name = "skills_configurations")
public class SkillConfigurationEntity extends BaseEntity {

    /** Application-generated PK: {@code sklc_<16-char-alphanumeric>}. */
    @Id
    @Column(nullable = false, length = 21)
    private String id;

    /** Foreign key to {@code mcp_configurations}. */
    @Column(nullable = false, length = 21)
    private String mcpConfigurationId;

    /** Human-readable skill name. */
    @Column(nullable = false, length = 255)
    private String name;

    /** Skill source — see {@link ConfigConstants.SkillSourceType} for valid values. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private SkillSourceType sourceType;

    /** File path or remote URL; nullable for INLINE skills. */
    @Column(columnDefinition = "TEXT")
    private String uri;

    /** Markdown skill content; primarily used for INLINE skills. */
    @Column(columnDefinition = "TEXT")
    private String content;

    /** Optional structured metadata (description, tags, configuration). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private JsonNode metadata;

    /** Active by default. */
    @Column(nullable = false)
    private Boolean active = true;

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getMcpConfigurationId() { return mcpConfigurationId; }
    public void setMcpConfigurationId(String mcpConfigurationId) { this.mcpConfigurationId = mcpConfigurationId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public SkillSourceType getSourceType() { return sourceType; }
    public void setSourceType(SkillSourceType sourceType) { this.sourceType = sourceType; }

    public String getUri() { return uri; }
    public void setUri(String uri) { this.uri = uri; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public JsonNode getMetadata() { return metadata; }
    public void setMetadata(JsonNode metadata) { this.metadata = metadata; }

    public Boolean getActive() { return active; }
    public void setActive(Boolean active) { this.active = active; }
}
