apiVersion: v1
kind: Secret
metadata:
  name: causa-db-secrets
  labels:
    app.kubernetes.io/name: causa-backend
type: Opaque
stringData:
  CAUSA_DB_USERNAME: "causa_backend"
  CAUSA_DB_PASSWORD: "password_here"

